# Generated by Django 4.0.4 on 2022-05-21 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trener', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='title',
        ),
        migrations.AlterField(
            model_name='exercise',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название упражнения'),
        ),
        migrations.AlterField(
            model_name='userexercise',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название упражнения'),
        ),
    ]
